export const CLONE_REDIRECTS: Array<{
  source: string;
  destination: string;
}> = [
  ...[
    "activesg-archery-range-booking-singapore",
    "activesg-athletics-track-booking-singapore",
    "activesg-badminton-court-booking-singapore",
    "activesg-bowling-booking-singapore",
    "activesg-climbing-wall-booking-singapore",
    "activesg-cricket-nets-booking-singapore",
    "activesg-cycling-circuit-booking-singapore",
    "activesg-fencing-booking-singapore",
    "activesg-football-futsal-booking-singapore",
    "activesg-gateball-petanque-booking-singapore",
    "activesg-gym-standard-rate-singapore",
    "activesg-holiday-camps-booking-singapore",
    "activesg-lawn-bowls-booking-singapore",
    "activesg-netball-booking-singapore",
    "activesg-pickleball-booking-singapore",
    "activesg-sepak-takraw-booking-singapore",
    "activesg-skating-booking-singapore",
    "activesg-squash-court-booking-singapore",
    "activesg-stadium-indoor-courts-singapore",
    "activesg-studio-dance-class-booking-singapore",
    "activesg-swimming-lessons-booking-singapore",
    "activesg-table-tennis-booking-singapore",
    "activesg-tennis-court-booking-singapore",
    "activesg-yoga-pilates-class-booking-singapore",
  ].map((slug) => ({
    source: `/guides/${slug}`,
    destination: "/guides/sports-fitness-singapore",
  })),
  ...[
    "international-school-book-fair-fundraising-ops-dual-career-singapore",
    "international-school-book-week-author-visit-ops-dual-career-singapore",
    "international-school-bus-pickup-dual-career-singapore",
    "international-school-concert-recital-ops-dual-career-singapore",
    "international-school-learning-support-waitlist-ops-dual-career-singapore",
    "international-school-lost-property-admin-portal-dual-career-singapore",
    "international-school-midyear-transfer-dual-career-singapore",
    "international-school-open-house-tour-ops-dual-career-singapore",
    "international-school-orientation-week-dual-career-singapore",
    "international-school-photo-day-ops-dual-career-singapore",
    "international-school-report-card-progress-meeting-dual-career-singapore",
    "international-school-residential-camp-overnight-trip-ops-dual-career-singapore",
    "international-school-speech-day-prize-giving-ops-dual-career-singapore",
    "international-school-sports-day-carnival-ops-dual-career-singapore",
    "international-school-winter-fair-bazaar-ops-dual-career-singapore",
    "kids-birthday-party-ops-dual-career-singapore",
  ].map((slug) => ({
    source: `/guides/${slug}`,
    destination: "/guides/international-schools-landscape",
  })),
  ...[
    "dual-career-chickenpox-varicella-school-exclusion-singapore",
    "dual-career-child-hospitalisation-coverage-singapore",
    "dual-career-dengue-child-fever-coverage-singapore",
    "dual-career-haze-psi-school-closure-coverage-singapore",
    "dual-career-head-lice-school-outbreak-singapore",
    "dual-career-helper-rest-day-sunday-coverage-singapore",
    "dual-career-hfmd-school-outbreak-coverage-singapore",
    "dual-career-kids-asthma-flare-coverage-singapore",
    "dual-career-kids-conjunctivitis-pink-eye-school-exclusion-singapore",
    "dual-career-kids-ear-infection-ent-coverage-singapore",
    "dual-career-kids-gastroenteritis-vomiting-diarrhoea-school-exclusion-singapore",
    "dual-career-kids-impetigo-school-exclusion-singapore",
    "dual-career-public-holiday-school-closed-coverage-singapore",
    "dual-career-sick-child-coverage-singapore",
    "exam-week-coverage-dual-career-singapore",
    "school-holiday-coverage-dual-career-singapore",
    "dual-career-post-hospitalisation-recovery-week-singapore",
    "dual-career-sibling-care-during-hospitalisation-singapore",
  ].map((slug) => ({
    source: `/guides/${slug}`,
    destination: "/guides/healthcare-gp-hospital",
  })),
  ...[
    "home-leave-jetlag-dual-career-family-singapore",
    "newborn-preschool-handoff-dual-career-singapore",
    "parent-teacher-conference-dual-career-singapore",
    "primary-cca-vs-external-academy-dual-career-singapore",
  ].map((slug) => ({
    source: `/guides/${slug}`,
    destination: "/guides/dual-career-spouse-singapore",
  })),
  ...[
    "activesg-swim-parent-belonging-singapore",
    "community-centre-parent-belonging-singapore",
    "dance-studio-waiting-parent-belonging-singapore",
    "faith-preschool-parent-belonging-singapore",
    "foodcourt-dinner-parent-belonging-singapore",
    "gymnastics-studio-waiting-parent-belonging-singapore",
    "hawker-breakfast-parent-belonging-singapore",
    "mall-indoor-playground-parent-belonging-singapore",
    "martial-arts-dojo-waiting-parent-belonging-singapore",
    "music-lesson-studio-waiting-parent-belonging-singapore",
    "nlb-library-parent-belonging-singapore",
    "park-playground-parent-belonging-singapore",
    "supermarket-evening-parent-belonging-singapore",
    "swim-school-waiting-area-parent-belonging-singapore",
    "tuition-centre-lobby-parent-belonging-singapore",
    "void-deck-kopi-parent-belonging-singapore",
    "wet-market-morning-parent-belonging-singapore",
    "youth-sports-sideline-parent-belonging-singapore",
  ].map((slug) => ({
    source: `/guides/${slug}`,
    destination: "/guides/find-my-people-singapore",
  })),
];

const CLONE_SLUGS = new Set(
  CLONE_REDIRECTS.map((item) => item.source.replace("/guides/", "")),
);

export function isCloneSlug(slug: string) {
  return CLONE_SLUGS.has(slug);
}
